<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
  <head><script src="color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Cover Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="../cover/login.css" rel="stylesheet">
   
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0" id="logine">Login</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="index.php" id="ini">Inicio</a>
        <a class="nav-link fw-bold py-1 px-0" href="cadastro.php" id="cad">Cadastre-se</a>
        <a class="nav-link fw-bold py-1 px-0" href="login.php" id="log">Login</a>
      
      </nav>
    </div>
  </header>

  <form action="botao">
    
    <input type="email" placeholder="Email" autofocus="true" id="escrita1" />

    <input type="password" placeholder="Senha" id="escrita2" />
    <button>Logar</button>
    <a href="cadastro.php" id="telacad">Não tenho conta</a>
    
</form> 
  </form>
  
   

<script src="bootstrap.bundle.min.js"></script>

    </body>
</html>
